'use strict';
(()=>{
const TYPES={basic:{name:'기본 타워',color:'#8fe4ef',cost:180,up:[150,230],damage:[20,33,52],range:[155,172,190],rate:[.75,.65,.55],desc:'균형 잡힌 공격 · 단일 대상'},magic:{name:'마법 타워',color:'#88d5bd',cost:220,up:[170,250],damage:[6,10,16],range:[140,155,170],rate:[.18,.16,.14],desc:'네모 공략 · 다른 적에게 피해 10%'},splash:{name:'범위공격 타워',color:'#ceabf1',cost:280,up:[200,300],damage:[34/3,55/3,84/3],range:[170,185,205],rate:[2.9/1.5,2.6/1.5,2.3/1.5],radius:[48,58,68],desc:'느린 포격 · 밀집한 적에게 폭발 피해'}};
const ENEMIES={normal:{hp:124,speed:48,reward:7.5,damage:1,color:'#dc9775',size:9},fast:{hp:80,speed:87,reward:9,damage:1,color:'#e5d379',size:10},armor:{hp:260,speed:32,reward:16.5,damage:3,color:'#98aaba',size:17},boss:{hp:2600,speed:23,reward:150,damage:20,color:'#dba2df',size:29}};
const WAVES=[["normal",26,.55,"armor",0],["normal",32,.52,"armor",1],["normal",28,.48,"fast",12,"armor",2],["normal",32,.46,"fast",16,"armor",3],["normal",38,.43,"fast",18,"armor",4],["normal",42,.4,"fast",20,"armor",5],["normal",48,.36,"fast",24,"armor",6],["normal",48,.34,"fast",28,"armor",7],["normal",58,.3,"fast",32,"armor",8],["normal",52,.32,"fast",30,"armor",9,"boss",1]];
// Seeded waves mix short patrols, dense bursts and breathing spaces.
function wavePlan(index,seed){let n=seed>>>0;const random=()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296;};const w=WAVES[index],types=Array(w[1]).fill(w[0]);for(let i=3;i<w.length;i+=2)types.push(...Array(w[i+1]).fill(w[i]));for(let i=types.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[types[i],types[j]]=[types[j],types[i]];}const armor=types.indexOf('armor');if(armor>5)[types[4],types[armor]]=[types[armor],types[4]];if(index===9){const bosses=types.filter(t=>t==='boss');for(let i=types.length-1;i>=0;i--)if(types[i]==='boss')types.splice(i,1);bosses.forEach((t,i)=>types.splice(12+i*32,0,t));}const gaps=[];let remaining=0,burst=false;for(let i=0;i<types.length;i++){if(remaining===0){burst=!burst;remaining=burst?7+Math.floor(random()*6):3+Math.floor(random()*3);}remaining--;gaps.push(remaining===0?w[2]*(2.8+random()*2.2):w[2]*(burst?.32+random()*.4:1.05+random()*.6));}const routes=types.map((type,i)=>(type==='boss'||(index===0&&type==='armor'))?0:(i===0?0:i===1?1:random()<.5?0:1));return{types,gaps,routes};}
const PATH=[[-35,116],[210,116],[210,295],[470,295],[470,135],[730,135],[730,465],[995,465]],PATHS=[PATH,[[-35,500],[70,500],[70,295],[210,295],...PATH.slice(3)]], SITES=[[100,200],[290,195],[360,385],[390,210],[560,220],[650,320],[810,245],[630,440],[825,380],[155,380],[570,65],[860,525],[150,480],[25,360]];
const ROUTES=PATHS.map(points=>{const segments=points.slice(1).map((p,i)=>Math.hypot(p[0]-points[i][0],p[1]-points[i][1]));return{points,segments,length:segments.reduce((a,b)=>a+b,0)};}),length=ROUTES[0].length;
function position(d,route=0){const{points,segments}=ROUTES[route];for(let i=0;i<segments.length;i++){if(d<=segments[i]){const q=d/segments[i];return{x:points[i][0]+(points[i+1][0]-points[i][0])*q,y:points[i][1]+(points[i+1][1]-points[i][1])*q};}d-=segments[i];}return{x:995,y:465};}
const TRAPS={bomb:{cost:100,radius:TYPES.splash.radius[0]},net:{cost:50,radius:24,duration:5}};let trapTool=null;let panelKey='';const $=id=>document.getElementById(id),canvas=$('board'),ctx=canvas.getContext('2d');let state,selected=-1,paused=false,muted=true,audio=null,last=0,bannerTime=0,musicTime=0,noticeTime=0;
function reset(){state={money:2400,hp:20,wave:0,mode:'ready',prep:20,queue:[],spawnGaps:[],spawnRoutes:[],seed:Math.floor(Math.random()*4294967296),spawn:0,enemies:[],traps:[],towers:[],shots:[],fx:[],kills:0,time:0};selected=-1;trapTool=null;panelKey="";paused=false;bannerTime=0;$('pause').textContent='일시정지';ui();}
function tone(freq,duration=.08,type='triangle',volume=.025){if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function message(t){$('notice').textContent=t;noticeTime=3;}function banner(t){$('banner').textContent=t;bannerTime=2.6;}function towerAt(){return state.towers.find(t=>t.site===selected);}
function effect(x,y,r,color,life=.3){if(state.fx.length<120)state.fx.push({x,y,r,color,life,max:life});}
function build(type){if(['menu','over','win'].includes(state.mode)||selected<0||towerAt())return false;const s=TYPES[type];if(state.money<s.cost){message('자금이 부족합니다.');return false;}state.money-=s.cost;const[x,y]=SITES[selected];state.towers.push({site:selected,type,level:0,x,y,cool:0,angle:0});effect(x,y,46,s.color,.6);tone(520,.14);ui();return true;}
function upgrade(){const t=towerAt();if(!t||t.level===2||['over','win','menu'].includes(state.mode))return false;const cost=TYPES[t.type].up[t.level];if(state.money<cost){message('업그레이드 자금이 부족합니다.');return false;}state.money-=cost;t.level++;effect(t.x,t.y,65,TYPES[t.type].color,.7);tone(740,.18);ui();return true;}
function ui(){for(const type of ['bomb','net']){const b=$(type);b.disabled=!['ready','active'].includes(state.mode)||state.money<TRAPS[type].cost;b.classList.toggle('armed',trapTool===type);b.setAttribute('aria-pressed',String(trapTool===type));}$('trap-help').textContent=trapTool?(trapTool==='bomb'?'폭탄':'그물')+' 선택 중 · 길을 터치해 설치 · 버튼을 다시 누르면 취소':'폭탄 / 그물 선택 → 길 위를 터치해 설치';$('money').textContent=state.money;$('hp').textContent=state.hp;$('hp').style.color=state.hp<=6?'#ff987d':'#edf4f4';$('wave').textContent=state.wave+' / 10';const t=towerAt(),key=[selected,state.money,t?.type,t?.level,state.mode].join(':');if(key!==panelKey){panelKey=key;$('cards').innerHTML='';$('detail').innerHTML='';if(t){const s=TYPES[t.type],l=t.level;$('selection').textContent=s.name+' · Lv.'+(l+1);$('description').textContent=s.desc;$('detail').innerHTML='<div class="detail"><div><small>공격력</small>'+Number(s.damage[l].toFixed(1))+'</div><div><small>사거리</small>'+s.range[l]+'</div><div><small>초당 발사</small>'+(1/s.rate[l]).toFixed(1)+'</div><div><small>'+(t.type==='splash'?'폭발 반경':'공격 방식')+'</small>'+(t.type==='splash'?s.radius[l]:(t.type==='magic'?'마법 · 단일 대상':'물리 · 단일 대상'))+'</div></div>';const b=document.createElement('button');b.className='primary';b.style.width='100%';b.style.marginTop='10px';b.textContent=l===2?'최고 레벨 · Lv.3':'업그레이드 → Lv.'+(l+2)+' · '+s.up[l];b.disabled=l===2||state.money<s.up[l]||['over','win'].includes(state.mode);b.onclick=upgrade;$('detail').append(b);}else{$('selection').textContent=selected<0?'설치 지점을 선택하세요':'설치 지점 '+(selected+1);$('description').textContent='굽이 안쪽은 여러 구간을 공격합니다. 기지 앞 타워로 마지막 방어선을 만드세요.';for(const[key,s]of Object.entries(TYPES)){const b=document.createElement('button');b.className='card';b.style.setProperty('--c',s.color);b.innerHTML='<strong>'+s.name+'<span>'+s.cost+'</span></strong><small>'+s.desc+'</small>';b.disabled=selected<0||state.money<s.cost||['menu','over','win'].includes(state.mode);b.onclick=()=>build(key);$('cards').append(b);}}}$('next').disabled=state.mode!=='ready';$('phase').textContent=state.mode==='ready'?'NEXT WAVE '+Math.ceil(state.prep)+'...':state.mode==='active'?'WAVE '+state.wave+' / 10 · 교전 중':state.mode==='win'?'전장 방어 완료':state.mode==='over'?'기지 방어 실패':'작전 대기';$('preview').textContent=state.mode==='ready'?['일반 적 공세 · 기본 타워 준비','증원과 네모 적 · 방어선을 넓히세요','빠른 적 등장 · 기본 타워로 공략','빠른 적 증가','불규칙한 혼합 공세 · 균형 있는 배치','혼합 편대 · 업그레이드','대규모 공세 · 범위공격 준비','고속 / 중장갑 동시 공세','연속 공세 · 방어선 최종 점검','BOSS 1기 · 마법 방어선 최종 점검'][state.wave]:state.mode==='active'?'남은 적 '+(state.enemies.length+state.queue.length)+' · 처치 '+state.kills:'10개 웨이브를 막아 기지를 지키세요.';}
function pathPoint(x,y){let best=null;for(const route of ROUTES)for(let i=0;i<route.points.length-1;i++){const[a,b]=[route.points[i],route.points[i+1]],dx=b[0]-a[0],dy=b[1]-a[1],q=Math.max(0,Math.min(1,((x-a[0])*dx+(y-a[1])*dy)/(dx*dx+dy*dy))),px=a[0]+q*dx,py=a[1]+q*dy,distance=Math.hypot(x-px,y-py);if(!best||distance<best.distance)best={x:px,y:py,distance};}return best;}
function placeTrap(type,x,y){if(!TRAPS[type]||!['ready','active'].includes(state.mode))return false;const p=pathPoint(x,y),spec=TRAPS[type];if(p.distance>24||p.x<0||p.x>960||p.y<0||p.y>590){message('길 위를 선택하세요.');return false;}if(state.money<spec.cost){message('자금이 부족합니다.');return false;}if(state.traps.some(t=>Math.hypot(t.x-p.x,t.y-p.y)<12)){message('다른 설치물과 조금 떨어진 곳을 선택하세요.');return false;}state.money-=spec.cost;state.traps.push({type,x:p.x,y:p.y,remaining:null});effect(p.x,p.y,24,'#e8ce91');tone(480);ui();return true;}
function updateTraps(dt){for(const t of state.traps){const spec=TRAPS[t.type];if(t.remaining!==null){t.remaining=Math.max(0,t.remaining-dt);if(t.remaining===0){t.done=true;continue;}}if(t.remaining===null&&state.enemies.some(e=>e.hp>0&&Math.hypot(e.x-t.x,e.y-t.y)<=10)){if(t.type==='bomb'){for(const e of state.enemies)if(e.hp>0&&Math.hypot(e.x-t.x,e.y-t.y)<=spec.radius)hit(e,e.hp,'bomb');effect(t.x,t.y,spec.radius,'#ffc677',.5);tone(70,.2,'triangle',.06);t.done=true;}else{t.remaining=spec.duration;effect(t.x,t.y,spec.radius,'#b9dcaa',.3);tone(260,.12);}}}state.traps=state.traps.filter(t=>!t.done);}
function drawTraps(){for(const t of state.traps){const r=TRAPS[t.type].radius;ctx.save();ctx.translate(t.x,t.y);ctx.strokeStyle=t.type==='bomb'?'#edc58e':'#c7dda8';ctx.lineWidth=1.5;ctx.setLineDash([4,4]);ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);if(t.type==='bomb'){ellipse(ctx,0,0,9,9,'#343b32');ellipse(ctx,-3,-3,3,3,'#929880');ctx.strokeStyle='#efd286';ctx.beginPath();ctx.moveTo(4,-6);ctx.lineTo(7,-13);ctx.stroke();ellipse(ctx,7,-13,2,2,'#ffa96c');}else{ctx.fillStyle=t.remaining!==null?'#a0cd8038':'#a0cd8018';ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.save();ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.clip();for(let v=-24;v<=24;v+=8){ctx.beginPath();ctx.moveTo(v,-24);ctx.lineTo(v,24);ctx.moveTo(-24,v);ctx.lineTo(24,v);ctx.stroke();}ctx.restore();if(t.remaining!==null){ctx.fillStyle='#fff3cf';ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillText(t.remaining.toFixed(1)+'s',0,-30);}}ctx.restore();}}
function startWave(){if(state.mode!=='ready'||paused)return;state.wave++;const w=WAVES[state.wave-1],plan=wavePlan(state.wave-1,state.seed+state.wave);state.queue=plan.types;state.spawnGaps=plan.gaps;state.spawnRoutes=plan.routes;state.interval=w[2];state.spawn=0;state.mode='active';banner(state.wave===10?'⚠ BOSS WAVE · HOLD THE LINE':'WAVE '+state.wave+' / 10');tone(180,.3,'sawtooth',.04);ui();}
function spawn(type,route=0){const s=ENEMIES[type],scale=(1+(state.wave-1)*.12)*(state.wave>=9?1.7:state.wave>=7?1.4:1);state.enemies.push({type,route,...s,hp:s.hp*scale,max:s.hp*scale,d:0,...position(0,route),flash:0});}
function hit(e,damage,attackType){if(e.hp<=0)return;const resistant=e.type==='armor'||e.type==='boss';const actual=damage*(attackType==='bomb'?1:((resistant&&attackType!=='magic')||(!resistant&&attackType==='magic')?.1:1));e.hp-=actual;e.flash=.12;if(e.hp<=0){state.money+=e.reward;state.kills++;effect(e.x,e.y,e.size*2,'#b7c6cb',.4);}}
function finish(win){state.mode=win?'win':'over';paused=false;$('overlay').hidden=false;$('overlay').innerHTML='<article><small>'+(win?'SECTOR SECURED':'DEFENSE LOST')+'</small><h1>'+(win?'VICTORY':'GAME OVER')+'</h1><p>'+(win?'10개 웨이브와 보스를 모두 막았습니다.':'기지가 함락되었습니다. 굽이 안쪽 배치와 업그레이드를 활용해 다시 도전하세요.')+'</p><p>WAVE '+state.wave+' / 10 · 처치 '+state.kills+' · 기지 HP '+state.hp+'</p><button class="primary" id="again">Play Again</button></article>';$('again').onclick=()=>{reset();$('overlay').hidden=true;};tone(win?660:100,.5);ui();}
function update(dt){if(paused||['menu','over','win'].includes(state.mode))return;state.time+=dt;bannerTime-=dt;if(bannerTime<=0)$('banner').textContent='';noticeTime-=dt;if(noticeTime<=0)$('notice').textContent='';musicTime-=dt;if(musicTime<=0){musicTime=state.wave>=7?.36:.65;tone([110,130.81,146.83,164.81][Math.floor(state.time*2)%4],.12,'sine',.018);}if(state.mode==='ready'){updateTraps(dt);state.prep-=dt;if(state.prep<=0)startWave();}else{state.spawn-=dt;if(state.queue.length&&state.spawn<=0){spawn(state.queue.shift(),state.spawnRoutes.shift()??0);state.spawn+=state.spawnGaps.shift()??state.interval;}updateTraps(dt);for(const e of state.enemies){if(e.hp<=0)continue;const held=state.traps.some(t=>t.type==='net'&&t.remaining>0&&Math.hypot(e.x-t.x,e.y-t.y)<=TRAPS.net.radius);if(!held)e.d+=e.speed*dt;Object.assign(e,position(e.d,e.route));e.flash=Math.max(0,e.flash-dt);if(e.d>=ROUTES[e.route].length){e.hp=0;state.hp=Math.max(0,state.hp-e.damage);effect(926,465,55,'#ff967f',.4);tone(85,.2);if(state.hp===0){finish(false);return;}}}}
for(const t of state.towers){t.cool-=dt;if(t.cool>0)continue;const s=TYPES[t.type],l=t.level;let target=null;for(const e of state.enemies)if(e.hp>0&&Math.hypot(e.x-t.x,e.y-t.y)<=s.range[l]&&(!target||ROUTES[e.route].length-e.d<ROUTES[target.route].length-target.d))target=e;if(target){t.angle=Math.atan2(target.y-t.y,target.x-t.x);t.cool=s.rate[l];state.shots.push({x:t.x,y:t.y,target,tx:target.x,ty:target.y,type:t.type,damage:s.damage[l],radius:s.radius?.[l]||0,speed:t.type==='splash'?360:650});tone(t.type==='magic'?500:t.type==='splash'?95:280,.04,'triangle',.012);}}
for(const b of state.shots){if(b.target.hp>0){b.tx=b.target.x;b.ty=b.target.y;}const d=Math.hypot(b.tx-b.x,b.ty-b.y);if(d<=b.speed*dt){b.done=true;if(b.radius){for(const e of state.enemies)if(e.hp>0&&Math.hypot(e.x-b.tx,e.y-b.ty)<=b.radius)hit(e,b.damage,b.type);effect(b.tx,b.ty,b.radius,'#c7a2ef',.4);tone(75,.12,'triangle',.035);}else{if(b.target.hp>0)hit(b.target,b.damage,b.type);effect(b.tx,b.ty,13,'#ecdeac',.16);}}else{b.x+=(b.tx-b.x)/d*b.speed*dt;b.y+=(b.ty-b.y)/d*b.speed*dt;}}
state.shots=state.shots.filter(b=>!b.done);state.enemies=state.enemies.filter(e=>e.hp>0);for(const f of state.fx)f.life-=dt;state.fx=state.fx.filter(f=>f.life>0);if(state.mode==='active'&&!state.queue.length&&!state.enemies.length&&!state.shots.length){if(state.wave===10){finish(true);return;}state.mode='ready';state.prep=state.wave>=7?9:14;state.money+=Math.floor((30+state.wave*3)/2);banner('WAVE CLEAR · 준비 보너스 지급');tone(560,.2);}}
function circle(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill();}
// Static scenery and unit art are cached; busy waves only composite sprites.
function ellipse(c,x,y,rx,ry,color){c.fillStyle=color;c.beginPath();c.ellipse(x,y,rx,ry,0,0,Math.PI*2);c.fill();}
function poly(c,points,color,outline='#302f28'){c.fillStyle=color;c.strokeStyle=outline;c.lineWidth=2;c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();c.fill();c.stroke();}
function stone(c,x,y,w,h){c.fillStyle='#5d6255';c.fillRect(x,y,w,h);c.fillStyle='#a5a28b';c.fillRect(x,y,w,3);c.strokeStyle='#393d35';c.lineWidth=1;c.strokeRect(x,y,w,h);}
function makeScenery(){const map=document.createElement('canvas');map.width=960;map.height=590;const c=map.getContext('2d');const bg=c.createLinearGradient(0,0,960,590);bg.addColorStop(0,'#637649');bg.addColorStop(.5,'#82915a');bg.addColorStop(1,'#465b3d');c.fillStyle=bg;c.fillRect(0,0,960,590);let seed=27;const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
function distance(x,y){let best=999;for(const path of PATHS)for(let i=1;i<path.length;i++){const[a,b]=[path[i-1],path[i]],dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((x-a[0])*dx+(y-a[1])*dy)/(dx*dx+dy*dy)));best=Math.min(best,Math.hypot(x-a[0]-t*dx,y-a[1]-t*dy));}return best;}
for(let i=0;i<1300;i++){const x=rnd()*960,y=rnd()*590;ellipse(c,x,y,5+rnd()*24,2+rnd()*8,rnd()<.5?'#354b3020':'#d3d59b16');}
c.lineJoin='round';c.lineCap='round';function road(w,color){c.lineWidth=w;c.strokeStyle=color;c.beginPath();for(const path of PATHS)path.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.stroke();}road(66,'#35452e');road(59,'#9a9267');road(49,'#b5a077');road(34,'#c4ae84');
for(let i=0;i<900;i++){const x=rnd()*960,y=rnd()*590;if(distance(x,y)<21)ellipse(c,x,y,1+rnd()*3,.8+rnd()*1.5,rnd()<.6?'#806e5140':'#e0ccaa70');}
for(let i=0;i<180;i++){const x=12+rnd()*930,y=20+rnd()*550;if(distance(x,y)<46||SITES.some(p=>Math.hypot(x-p[0],y-p[1])<43)||x>865&&y>385)continue;if(rnd()<.35){ellipse(c,x+3,y+4,12,5,'#23322645');poly(c,[[x-9,y+2],[x-6,y-8],[x+3,y-12],[x+11,y-3],[x+8,y+5]],'#888d76');poly(c,[[x-6,y-8],[x+3,y-12],[x+11,y-3],[x,y-4]],'#b3b49a');}else{const size=12+rnd()*14;ellipse(c,x+5,y+10,size,7,'#24392355');c.fillStyle='#64523a';c.fillRect(x-3,y-5,6,16);ellipse(c,x,y-10,size,size*.78,'#2f5037');ellipse(c,x-5,y-15,size*.8,size*.62,'#456746');ellipse(c,x+5,y-20,size*.65,size*.55,'#658453');}}
for(const [x,y]of [[20,74],[20,550]]){c.fillStyle='#55422c';c.fillRect(x+5,y-22,4,35);poly(c,[[x-3,y-24],[x+45,y-24],[x+50,y-14],[x+45,y-4],[x-3,y-4]],'#8a6340');c.fillStyle='#f0d8a4';c.font='bold 10px system-ui';c.fillText(y<100?'NORTH':'SOUTH',x+1,y-10);}
// Fortress gate, parapets and banners.
ellipse(c,927,481,53,25,'#28362770');stone(c,892,418,68,76);stone(c,886,413,22,86);stone(c,944,413,22,86);for(let x=884;x<965;x+=14)stone(c,x,404,10,15);poly(c,[[885,410],[897,392],[909,410]],'#61514b');poly(c,[[943,410],[955,392],[967,410]],'#61514b');c.fillStyle='#292d26';c.fillRect(913,441,27,53);c.beginPath();c.arc(926,443,14,Math.PI,0);c.fill();c.fillStyle='#766047';c.fillRect(916,446,21,48);for(let x=918;x<937;x+=5){c.fillStyle='#3e342a';c.fillRect(x,446,2,48);}c.fillStyle='#d3bb76';c.fillRect(914,465,26,3);for(const x of [896,953]){c.fillStyle='#263e37';c.fillRect(x-5,425,10,24);poly(c,[[x-5,449],[x+5,449],[x,454]],'#263e37');}return map;}
function towerSprite(type,level){const a=document.createElement('canvas');a.width=100;a.height=110;const c=a.getContext('2d');c.translate(50,75);ellipse(c,4,10,31,12,'#17231d70');ellipse(c,0,3,27,13,'#6c6854');ellipse(c,0,0,27,11,'#b8ad87');const h=26+level*5;stone(c,-18,-h,36,h);for(let row=0;row<3;row++)for(let col=0;col<3;col++){c.strokeStyle='#494e43';c.beginPath();c.moveTo(-17+col*12+(row%2?5:0),-h+row*10);c.lineTo(-17+col*12+(row%2?5:0),-h+row*10+9);c.stroke();}ellipse(c,0,-h,20,10,'#c6bc98');
if(type==='basic'){poly(c,[[-24,-h-2],[0,-h-22],[24,-h-2],[0,-h+5]],'#8c4e35');poly(c,[[0,-h-22],[24,-h-2],[0,-h+5]],'#613d30');c.fillStyle='#252d24';c.fillRect(-7,-h+8,14,12);for(let i=0;i<=level;i++){c.fillStyle='#d5bd7a';c.fillRect(-13+i*9,-h+2,5,5);}}
else if(type==='magic'){stone(c,-10,-h-20,20,22);poly(c,[[-13,-h-17],[0,-h-39],[13,-h-17],[0,-h-7]],'#69b5ab','#304d48');poly(c,[[0,-h-39],[13,-h-17],[0,-h-7]],'#378a87','#304d48');poly(c,[[-9,-h-18],[0,-h-34],[0,-h-11]],'#b5f5d9','#739e85');for(const x of [-22,22]){stone(c,x-3,-h-7,6,14);ellipse(c,x,-h-9,4,5,'#97e6c8');}}
else{poly(c,[[-23,-h],[0,-h-11],[23,-h],[0,-h+11]],'#9c8256');c.fillStyle='#57412b';c.fillRect(-22,-h+1,44,8);for(const x of [-15,15]){ellipse(c,x,-h+8,8,8,'#3c352b');ellipse(c,x,-h+8,4,4,'#b39d6e');}}
for(let i=0;i<=level;i++){ellipse(c,-8+i*8,10,2.5,2.5,'#ead699');}return a;}
function enemySprite(type,frame){const a=document.createElement('canvas');a.width=90;a.height=140;const c=a.getContext('2d');c.translate(45,95);const boss=type==='boss',armored=type==='armor'||boss,k=boss?1.6:type==='normal'?.78:1;c.scale(k,k);const step=frame?3:-3;ellipse(c,3,5,armored?17:12,6,'#17231b60');c.fillStyle='#3d332d';c.fillRect(-9,-1+step,7,9);c.fillRect(3,-1-step,7,9);
if(armored){poly(c,[[-16,-29],[12,-29],[17,-21],[17,-3],[-16,-3]],boss?'#6e5966':'#737f76');poly(c,[[-16,-29],[12,-29],[17,-21],[-12,-21]],'#b5b9a0');stone(c,-12,-41,23,16);c.fillStyle='#233130';c.fillRect(-8,-34,16,4);c.fillStyle='#a2f4d0';c.fillRect(-6,-34,4,3);c.fillRect(3,-34,4,3);poly(c,[[-22,-22],[-9,-22],[-9,-2],[-22,-2]],'#596b65');poly(c,[[-19,-19],[-12,-19],[-12,-6],[-19,-6]],'#8dbfb0');poly(c,[[0,-22],[7,-15],[0,-8],[-7,-15]],'#9fe2ce');if(boss){poly(c,[[-15,-42],[-19,-53],[-5,-44]],'#d0ba8d');poly(c,[[11,-42],[17,-53],[3,-44]],'#d0ba8d');}}
else{const fast=type==='fast';if(fast){poly(c,[[-11,-27],[10,-27],[13,-7],[-12,-7]],'#a88d4a');}else{ellipse(c,0,-17,12,14,'#8a5140');ellipse(c,-3,-20,7,10,'#9a604b');}c.fillStyle='#4c4332';c.fillRect(-11,-9,22,4);ellipse(c,0,-33,9,10,'#c39b72');if(fast){poly(c,[[-12,-29],[0,-48],[13,-29],[7,-26],[0,-34],[-6,-26]],'#7a773e');}else{ellipse(c,0,-37,10,6,'#657469');c.fillStyle='#9da592';c.fillRect(-10,-38,20,3);}c.fillStyle='#342e26';c.fillRect(-5,-33,3,2);c.fillRect(3,-33,3,2);c.strokeStyle='#615344';c.lineCap='round';c.lineJoin='round';c.lineWidth=5;c.beginPath();c.moveTo(-10,-24);c.lineTo(-16,-14+step);c.moveTo(10,-24);c.lineTo(16,-16-step);c.stroke();c.strokeStyle='#c8c4a8';c.lineWidth=3;c.beginPath();c.moveTo(16,-15-step);c.lineTo(19,-33-step);c.stroke();}return a;}
const scenery=makeScenery(),towerArt=Object.fromEntries(Object.keys(TYPES).map(t=>[t,[0,1,2].map(l=>towerSprite(t,l))])),enemyArt=Object.fromEntries(Object.keys(ENEMIES).map(t=>[t,[0,1].map(f=>enemySprite(t,f))]));
function draw(){ctx.clearRect(0,0,960,590);ctx.drawImage(scenery,0,0);drawTraps();const chosen=towerAt();if(chosen){circle(chosen.x,chosen.y,TYPES[chosen.type].range[chosen.level],TYPES[chosen.type].color+'18');ctx.strokeStyle='#e6dbaf99';ctx.lineWidth=2;ctx.beginPath();ctx.arc(chosen.x,chosen.y,TYPES[chosen.type].range[chosen.level],0,Math.PI*2);ctx.stroke();}
SITES.forEach(([x,y],i)=>{if(state.towers.some(t=>t.site===i))return;ellipse(ctx,x+3,y+5,26,12,'#2b392d55');ellipse(ctx,x,y,25,13,i===selected?'#e1c88e':'#a89b73');ctx.strokeStyle=i===selected?'#fff2bf':'#625c44';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x,y,25,13,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#574e39';ctx.font='bold 22px system-ui';ctx.textAlign='center';ctx.fillText('+',x,y+7);ctx.textAlign='left';});
// Depth order lets soldiers pass in front of buildings naturally.
const actors=[...state.towers.map(t=>({y:t.y,t})),...state.enemies.map(e=>({y:e.y,e}))].sort((a,b)=>a.y-b.y);
for(const actor of actors){if(actor.t){const t=actor.t;ctx.drawImage(towerArt[t.type][t.level],t.x-50,t.y-75);if(t.type!=='magic'){ctx.save();ctx.translate(t.x,t.y-29-t.level*5);ctx.rotate(t.angle);ctx.strokeStyle='#292f29';ctx.lineWidth=t.type==='splash'?11:5;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-7,0);ctx.lineTo(t.type==='splash'?24:18,0);ctx.stroke();ctx.strokeStyle=t.type==='splash'?'#8e9689':'#baab7c';ctx.lineWidth=t.type==='splash'?5:2;ctx.beginPath();ctx.moveTo(-7,-2);ctx.lineTo(20,-2);ctx.stroke();ctx.restore();}}
else{const e=actor.e;ctx.drawImage(enemyArt[e.type][Math.floor(e.d/8)%2],e.x-45,e.y-95);if(e.flash>0){ellipse(ctx,e.x,e.y-19,e.size*.9,e.size*.8,'#fff8d470');}const boss=e.type==='boss',w=boss?65:30,y=e.y-(boss?88:50);ctx.fillStyle='#20281e';ctx.fillRect(e.x-w/2-1,y-1,w+2,6);ctx.fillStyle=boss?'#e29a79':'#b4d27d';ctx.fillRect(e.x-w/2,y,w*Math.max(0,e.hp/e.max),4);if(boss){ctx.fillStyle='#fff0cb';ctx.font='bold 10px system-ui';ctx.textAlign='center';ctx.fillText('BOSS',e.x,y-6);ctx.textAlign='left';}}}
for(const b of state.shots){if(b.type==='magic'){circle(b.x,b.y,9,'#8fead32b');circle(b.x,b.y,4,'#d7fff3');ctx.strokeStyle='#72d3bf';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(b.x-7,b.y+4);ctx.lineTo(b.x,b.y);ctx.stroke();}else if(b.type==='splash'){circle(b.x+2,b.y+3,6,'#1d241d55');circle(b.x,b.y,5,'#373b33');circle(b.x-1,b.y-2,2,'#a3a994');}else{const angle=Math.atan2(b.ty-b.y,b.tx-b.x);ctx.strokeStyle='#f8e2ac';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(b.x-Math.cos(angle)*12,b.y-Math.sin(angle)*12);ctx.lineTo(b.x,b.y);ctx.stroke();}}
for(const f of state.fx){const q=1-f.life/f.max;ctx.globalAlpha=1-q;ctx.strokeStyle=f.color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(f.x,f.y,f.r*q+3,0,Math.PI*2);ctx.stroke();if(f.r>=40){for(let i=0;i<6;i++){const a=i*Math.PI/3;ellipse(ctx,f.x+Math.cos(a)*f.r*q*.7,f.y+Math.sin(a)*f.r*q*.5,5+q*9,4+q*6,f.color==='#c7a2ef'?'#d8ae7370':'#dee1cd60');}}else{ctx.fillStyle='#fff0bb';ctx.fillRect(f.x-2,f.y-7-q*4,4,12);}ctx.globalAlpha=1;}
if(state.hp<=6){ctx.strokeStyle='#d2664299';ctx.lineWidth=8;ctx.strokeRect(4,4,952,582);}if(paused){ctx.fillStyle='#14201899';ctx.fillRect(0,0,960,590);ctx.textAlign='center';ctx.fillStyle='#fff4d9';ctx.font='bold 36px system-ui';ctx.fillText('PAUSED',480,295);ctx.textAlign='left';}}
canvas.addEventListener('pointerdown',e=>{if(['menu','over','win'].includes(state.mode))return;const r=canvas.getBoundingClientRect(),scale=Math.min(r.width/960,r.height/590),full=matchMedia('(orientation:landscape) and (max-height:600px)').matches,x=full?(e.clientX-r.left)*960/r.width:(e.clientX-r.left-(r.width-960*scale)/2)/scale,y=full?(e.clientY-r.top)*590/r.height:(e.clientY-r.top-(r.height-590*scale)/2)/scale;if(x<0||x>960||y<0||y>590)return;if(trapTool){placeTrap(trapTool,x,y);return;}let nearest=-1,best=Infinity;SITES.forEach((p,i)=>{const distance=Math.hypot(p[0]-x,p[1]-y);if(distance<=Math.max(32,22/scale)&&distance<best){nearest=i;best=distance;}});selected=nearest;ui();});for(const type of ['bomb','net'])$(type).onclick=()=>{trapTool=trapTool===type?null:type;ui();};$('next').onclick=startWave;$('pause').onclick=()=>{if(['menu','over','win'].includes(state.mode))return;paused=!paused;$('pause').textContent=paused?'계속하기':'일시정지';};$('mute').onclick=()=>{muted=!muted;$('mute').textContent=muted?'음소거':'사운드 ON';tone(440,.12);};async function enterFullscreen(showHelp=true){try{if(document.fullscreenElement){await document.exitFullscreen();return;}if(!document.documentElement.requestFullscreen){if(showHelp)$('display-help').showModal();return;}await document.documentElement.requestFullscreen({navigationUI:'hide'});try{await screen.orientation?.lock?.('landscape');}catch{}}catch{if(showHelp)$('display-help').showModal();}}
$('fullscreen').onclick=()=>enterFullscreen();$('close-display-help').onclick=()=>$('display-help').close();document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'전체화면 종료':'전체화면';});
$('start').onclick=()=>{if(matchMedia('(pointer:coarse)').matches)enterFullscreen(false);reset();$('overlay').hidden=true;};document.addEventListener('visibilitychange',()=>{if(document.hidden&&!['menu','over','win'].includes(state.mode)){paused=true;$('pause').textContent='계속하기';}});reset();state.mode='menu';ui();let refresh=0;function frame(ts){const dt=Math.min(.05,(ts-last)/1000||0);last=ts;update(dt);refresh+=dt;if(refresh>.2){ui();refresh=0;}draw();requestAnimationFrame(frame);}requestAnimationFrame(frame);
if(location.search.includes('test'))window.qa={get state(){return state;},reset,build,upgrade,placeTrap,startWave,spawn,update,position,length,select(i){selected=i;ui();},spec:{TRAPS,TYPES,ENEMIES,WAVES,SITES,PATHS,ROUTES},wavePlan,hit,stop(){paused=true;},run(dt){paused=false;update(dt);paused=true;}};
})();




