'use strict';
(()=>{
const TYPES={basic:{name:'기본 타워',color:'#8fe4ef',cost:90,up:[75,115],damage:[20,33,52],range:[155,172,190],rate:[.75,.65,.55],desc:'균형 잡힌 공격 · 단일 대상'},rapid:{name:'연사 타워',color:'#e7c779',cost:110,up:[85,125],damage:[6,10,16],range:[140,155,170],rate:[.18,.16,.14],desc:'빠른 발사 · 약한 적과 빠른 적'},splash:{name:'범위공격 타워',color:'#ceabf1',cost:140,up:[100,150],damage:[34,55,84],range:[170,185,205],rate:[1.45,1.3,1.15],radius:[48,58,68],desc:'느린 포격 · 밀집한 적에게 폭발 피해'}};
const ENEMIES={normal:{hp:62,speed:48,reward:10,damage:1,color:'#dc9775',size:12},fast:{hp:40,speed:87,reward:12,damage:1,color:'#e5d379',size:10},armor:{hp:260,speed:32,reward:22,damage:3,color:'#98aaba',size:17},boss:{hp:2600,speed:23,reward:200,damage:20,color:'#dba2df',size:29}};
const WAVES=[['normal',8,.95],['normal',12,.85],['normal',10,.7,'fast',5],['normal',12,.65,'fast',9],['normal',12,.62,'armor',4],['normal',14,.55,'fast',8,'armor',5],['normal',32,.3,'fast',10,'armor',5],['fast',22,.38,'armor',10,'normal',10],['normal',30,.25,'fast',20,'armor',12],['normal',22,.38,'fast',16,'armor',10,'boss',1]];
const PATH=[[-35,116],[210,116],[210,295],[470,295],[470,135],[730,135],[730,465],[995,465]], SITES=[[100,200],[290,195],[360,385],[390,210],[560,220],[650,320],[810,245],[630,440],[825,380],[155,380],[570,65],[860,525]];
const seg=PATH.slice(1).map((p,i)=>Math.hypot(p[0]-PATH[i][0],p[1]-PATH[i][1])),length=seg.reduce((a,b)=>a+b,0);
function position(d){for(let i=0;i<seg.length;i++){if(d<=seg[i]){const q=d/seg[i];return{x:PATH[i][0]+(PATH[i+1][0]-PATH[i][0])*q,y:PATH[i][1]+(PATH[i+1][1]-PATH[i][1])*q};}d-=seg[i];}return{x:995,y:465};}
let panelKey='';const $=id=>document.getElementById(id),canvas=$('board'),ctx=canvas.getContext('2d');let state,selected=-1,paused=false,muted=true,audio=null,last=0,bannerTime=0,musicTime=0,noticeTime=0;
function reset(){state={money:300,hp:20,wave:0,mode:'ready',prep:20,queue:[],spawn:0,enemies:[],towers:[],shots:[],fx:[],kills:0,time:0};selected=-1;paused=false;bannerTime=0;$('pause').textContent='일시정지';ui();}
function tone(freq,duration=.08,type='triangle',volume=.025){if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function message(t){$('notice').textContent=t;noticeTime=3;}function banner(t){$('banner').textContent=t;bannerTime=2.6;}function towerAt(){return state.towers.find(t=>t.site===selected);}
function effect(x,y,r,color,life=.3){if(state.fx.length<120)state.fx.push({x,y,r,color,life,max:life});}
function build(type){if(['menu','over','win'].includes(state.mode)||selected<0||towerAt())return false;const s=TYPES[type];if(state.money<s.cost){message('자금이 부족합니다.');return false;}state.money-=s.cost;const[x,y]=SITES[selected];state.towers.push({site:selected,type,level:0,x,y,cool:0,angle:0});effect(x,y,46,s.color,.6);tone(520,.14);ui();return true;}
function upgrade(){const t=towerAt();if(!t||t.level===2||['over','win','menu'].includes(state.mode))return false;const cost=TYPES[t.type].up[t.level];if(state.money<cost){message('업그레이드 자금이 부족합니다.');return false;}state.money-=cost;t.level++;effect(t.x,t.y,65,TYPES[t.type].color,.7);tone(740,.18);ui();return true;}
function ui(){$('money').textContent=state.money;$('hp').textContent=state.hp;$('hp').style.color=state.hp<=6?'#ff987d':'#edf4f4';$('wave').textContent=state.wave+' / 10';const t=towerAt(),key=[selected,state.money,t?.type,t?.level,state.mode].join(':');if(key!==panelKey){panelKey=key;$('cards').innerHTML='';$('detail').innerHTML='';if(t){const s=TYPES[t.type],l=t.level;$('selection').textContent=s.name+' · Lv.'+(l+1);$('description').textContent=s.desc;$('detail').innerHTML='<div class="detail"><div><small>공격력</small>'+s.damage[l]+'</div><div><small>사거리</small>'+s.range[l]+'</div><div><small>초당 발사</small>'+(1/s.rate[l]).toFixed(1)+'</div><div><small>'+(t.type==='splash'?'폭발 반경':'공격 방식')+'</small>'+(t.type==='splash'?s.radius[l]:'단일 대상')+'</div></div>';const b=document.createElement('button');b.className='primary';b.style.width='100%';b.style.marginTop='10px';b.textContent=l===2?'최고 레벨 · Lv.3':'업그레이드 → Lv.'+(l+2)+' · '+s.up[l];b.disabled=l===2||state.money<s.up[l]||['over','win'].includes(state.mode);b.onclick=upgrade;$('detail').append(b);}else{$('selection').textContent=selected<0?'설치 지점을 선택하세요':'설치 지점 '+(selected+1);$('description').textContent='굽이 안쪽은 여러 구간을 공격합니다. 기지 앞 타워로 마지막 방어선을 만드세요.';for(const[key,s]of Object.entries(TYPES)){const b=document.createElement('button');b.className='card';b.style.setProperty('--c',s.color);b.innerHTML='<strong>'+s.name+'<span>'+s.cost+'</span></strong><small>'+s.desc+'</small>';b.disabled=selected<0||state.money<s.cost||['menu','over','win'].includes(state.mode);b.onclick=()=>build(key);$('cards').append(b);}}}$('next').disabled=state.mode!=='ready';$('phase').textContent=state.mode==='ready'?'NEXT WAVE '+Math.ceil(state.prep)+'...':state.mode==='active'?'WAVE '+state.wave+' / 10 · 교전 중':state.mode==='win'?'전장 방어 완료':state.mode==='over'?'기지 방어 실패':'작전 대기';$('preview').textContent=state.mode==='ready'?['일반 적 · 기본 방어선 확보','일반 적 증가 · 배치를 넓히세요','빠른 적 등장 · 연사 준비','빠른 적 증가','중장갑 등장 · 공격력 강화','혼합 편대 · 업그레이드','대규모 공세 · 범위공격 준비','고속 / 중장갑 동시 공세','연속 공세 · 방어선 최종 점검','BOSS · 마지막 방어선'][state.wave]:state.mode==='active'?'남은 적 '+(state.enemies.length+state.queue.length)+' · 처치 '+state.kills:'10개 웨이브를 막아 기지를 지키세요.';}
function startWave(){if(state.mode!=='ready'||paused)return;state.wave++;const w=WAVES[state.wave-1],groups=Array(w[1]).fill(w[0]);for(let i=3;i<w.length;i+=2)for(let n=0;n<w[i+1];n++)groups.splice(Math.min(groups.length,Math.floor((n+.5)*groups.length/w[i+1])),0,w[i]);if(state.wave===10){groups.splice(groups.indexOf('boss'),1);groups.splice(10,0,'boss');}state.queue=groups;state.interval=w[2];state.spawn=0;state.mode='active';banner(state.wave===10?'⚠ BOSS WAVE · HOLD THE LINE':'WAVE '+state.wave+' / 10');tone(180,.3,'sawtooth',.04);ui();}
function spawn(type){const s=ENEMIES[type],scale=(1+(state.wave-1)*.12)*(state.wave>=9?1.7:state.wave>=7?1.4:1);state.enemies.push({type,...s,hp:s.hp*scale,max:s.hp*scale,d:0,...position(0),flash:0});}
function hit(e,damage){if(e.hp<=0)return;e.hp-=damage;e.flash=.12;if(e.hp<=0){state.money+=e.reward;state.kills++;effect(e.x,e.y,e.size*2,'#b7c6cb',.4);}}
function finish(win){state.mode=win?'win':'over';paused=false;$('overlay').hidden=false;$('overlay').innerHTML='<article><small>'+(win?'SECTOR SECURED':'DEFENSE LOST')+'</small><h1>'+(win?'VICTORY':'GAME OVER')+'</h1><p>'+(win?'10개 웨이브와 보스를 모두 막았습니다.':'기지가 함락되었습니다. 굽이 안쪽 배치와 업그레이드를 활용해 다시 도전하세요.')+'</p><p>WAVE '+state.wave+' / 10 · 처치 '+state.kills+' · 기지 HP '+state.hp+'</p><button class="primary" id="again">Play Again</button></article>';$('again').onclick=()=>{reset();$('overlay').hidden=true;};tone(win?660:100,.5);ui();}
function update(dt){if(paused||['menu','over','win'].includes(state.mode))return;state.time+=dt;bannerTime-=dt;if(bannerTime<=0)$('banner').textContent='';noticeTime-=dt;if(noticeTime<=0)$('notice').textContent='';musicTime-=dt;if(musicTime<=0){musicTime=state.wave>=7?.36:.65;tone([110,130.81,146.83,164.81][Math.floor(state.time*2)%4],.12,'sine',.018);}if(state.mode==='ready'){state.prep-=dt;if(state.prep<=0)startWave();}else{state.spawn-=dt;if(state.queue.length&&state.spawn<=0){spawn(state.queue.shift());state.spawn+=state.interval;}for(const e of state.enemies){if(e.hp<=0)continue;e.d+=e.speed*dt;Object.assign(e,position(e.d));e.flash=Math.max(0,e.flash-dt);if(e.d>=length){e.hp=0;state.hp=Math.max(0,state.hp-e.damage);effect(926,465,55,'#ff967f',.4);tone(85,.2);if(state.hp===0){finish(false);return;}}}}
for(const t of state.towers){t.cool-=dt;if(t.cool>0)continue;const s=TYPES[t.type],l=t.level;let target=null;for(const e of state.enemies)if(e.hp>0&&Math.hypot(e.x-t.x,e.y-t.y)<=s.range[l]&&(!target||e.d>target.d))target=e;if(target){t.angle=Math.atan2(target.y-t.y,target.x-t.x);t.cool=s.rate[l];state.shots.push({x:t.x,y:t.y,target,tx:target.x,ty:target.y,type:t.type,damage:s.damage[l],radius:s.radius?.[l]||0,speed:t.type==='splash'?360:650});tone(t.type==='rapid'?500:t.type==='splash'?95:280,.04,'triangle',.012);}}
for(const b of state.shots){if(b.target.hp>0){b.tx=b.target.x;b.ty=b.target.y;}const d=Math.hypot(b.tx-b.x,b.ty-b.y);if(d<=b.speed*dt){b.done=true;if(b.radius){for(const e of state.enemies)if(e.hp>0&&Math.hypot(e.x-b.tx,e.y-b.ty)<=b.radius)hit(e,b.damage);effect(b.tx,b.ty,b.radius,'#c7a2ef',.4);tone(75,.12,'triangle',.035);}else{if(b.target.hp>0)hit(b.target,b.damage);effect(b.tx,b.ty,13,'#ecdeac',.16);}}else{b.x+=(b.tx-b.x)/d*b.speed*dt;b.y+=(b.ty-b.y)/d*b.speed*dt;}}
state.shots=state.shots.filter(b=>!b.done);state.enemies=state.enemies.filter(e=>e.hp>0);for(const f of state.fx)f.life-=dt;state.fx=state.fx.filter(f=>f.life>0);if(state.mode==='active'&&!state.queue.length&&!state.enemies.length&&!state.shots.length){if(state.wave===10){finish(true);return;}state.mode='ready';state.prep=state.wave>=7?9:14;state.money+=30+state.wave*3;banner('WAVE CLEAR · 준비 보너스 지급');tone(560,.2);}}
function circle(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill();}
function draw(){ctx.clearRect(0,0,960,590);ctx.fillStyle='#183038';ctx.fillRect(0,0,960,590);ctx.strokeStyle='#29414a';ctx.lineWidth=1;for(let x=0;x<960;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,590);ctx.stroke();}for(let y=0;y<590;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(960,y);ctx.stroke();}ctx.lineJoin='round';ctx.lineCap='round';function road(width,color){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();PATH.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();}road(62,'#102129');road(49,'#697373');road(36,'#586463');ctx.setLineDash([7,17]);road(2,'#a4aaa080');ctx.setLineDash([]);ctx.fillStyle='#edc288';ctx.font='bold 12px system-ui';ctx.fillText('ENTRY →',18,76);ctx.fillStyle='#233e4b';ctx.fillRect(898,416,60,96);ctx.strokeStyle='#99dbe1';ctx.lineWidth=2;ctx.strokeRect(898,416,60,96);ctx.fillStyle=state.hp<=6?'#ff937d':'#9ce5de';ctx.fillRect(913,435,30,40);ctx.fillStyle='#d8edf0';ctx.font='bold 11px system-ui';ctx.fillText('BASE',912,500);if(selected>=0){const t=towerAt();if(t){circle(t.x,t.y,TYPES[t.type].range[t.level],TYPES[t.type].color+'15');ctx.strokeStyle=TYPES[t.type].color+'80';ctx.lineWidth=1;ctx.beginPath();ctx.arc(t.x,t.y,TYPES[t.type].range[t.level],0,7);ctx.stroke();}}
SITES.forEach(([x,y],i)=>{circle(x,y,25,i===selected?'#43616b':'#122832');ctx.strokeStyle=i===selected?'#d9f0aa':'#53727c';ctx.lineWidth=i===selected?3:2;ctx.beginPath();ctx.arc(x,y,25,0,7);ctx.stroke();if(!state.towers.some(t=>t.site===i)){ctx.fillStyle='#92b0b9';ctx.font='22px system-ui';ctx.textAlign='center';ctx.fillText('+',x,y+7);ctx.textAlign='left';}});for(const t of state.towers){const s=TYPES[t.type];circle(t.x,t.y,20,'#0c1b24');ctx.save();ctx.translate(t.x,t.y);ctx.rotate(t.angle);ctx.fillStyle=s.color;ctx.fillRect(-10,-11,21,22);ctx.fillStyle='#dee8e5';if(t.type==='rapid'){ctx.fillRect(5,-8,26+t.level*3,4);ctx.fillRect(5,4,26+t.level*3,4);}else ctx.fillRect(3,-(t.type==='splash'?7:4),28+t.level*4,t.type==='splash'?14:8);circle(0,0,8,s.color);ctx.restore();for(let n=0;n<=t.level;n++)circle(t.x-7+n*7,t.y+30,2.5,s.color);}
for(const e of state.enemies){ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle=e.flash>0?'#fff':e.color;ctx.strokeStyle='#11212a';ctx.lineWidth=3;if(e.type==='fast'){ctx.beginPath();ctx.moveTo(e.size,0);ctx.lineTo(-e.size,-e.size);ctx.lineTo(-e.size,e.size);ctx.closePath();ctx.fill();ctx.stroke();}else if(e.type==='normal'){ctx.beginPath();ctx.arc(0,0,e.size,0,7);ctx.fill();ctx.stroke();}else{ctx.fillRect(-e.size,-e.size,e.size*2,e.size*2);ctx.strokeRect(-e.size,-e.size,e.size*2,e.size*2);ctx.fillStyle='#263945';ctx.fillRect(-e.size*.5,-e.size*.5,e.size,e.size);}const w=e.type==='boss'?65:30;ctx.fillStyle='#101b23';ctx.fillRect(-w/2,-e.size-12,w,5);ctx.fillStyle=e.type==='boss'?'#e6a7e5':'#b9e18c';ctx.fillRect(-w/2,-e.size-12,w*Math.max(0,e.hp/e.max),5);if(e.type==='boss'){ctx.fillStyle='#f6d5ed';ctx.font='bold 10px system-ui';ctx.fillText('BOSS',-15,-e.size-17);}ctx.restore();}for(const b of state.shots)circle(b.x,b.y,b.radius?6:3,TYPES[b.type].color);for(const f of state.fx){ctx.globalAlpha=f.life/f.max;ctx.strokeStyle=f.color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(f.x,f.y,f.r*(1-f.life/f.max)+3,0,7);ctx.stroke();ctx.globalAlpha=1;}if(paused){ctx.fillStyle='#0b1729aa';ctx.fillRect(0,0,960,590);ctx.textAlign='center';ctx.fillStyle='#eff6f4';ctx.font='bold 36px system-ui';ctx.fillText('PAUSED',480,295);ctx.textAlign='left';}}
canvas.addEventListener('pointerdown',e=>{if(['menu','over','win'].includes(state.mode))return;const r=canvas.getBoundingClientRect(),scale=Math.min(r.width/960,r.height/590),x=(e.clientX-r.left-(r.width-960*scale)/2)/scale,y=(e.clientY-r.top-(r.height-590*scale)/2)/scale;if(x<0||x>960||y<0||y>590)return;let nearest=-1,best=Infinity;SITES.forEach((p,i)=>{const distance=Math.hypot(p[0]-x,p[1]-y);if(distance<=Math.max(32,22/scale)&&distance<best){nearest=i;best=distance;}});selected=nearest;ui();});$('next').onclick=startWave;$('pause').onclick=()=>{if(['menu','over','win'].includes(state.mode))return;paused=!paused;$('pause').textContent=paused?'계속하기':'일시정지';};$('mute').onclick=()=>{muted=!muted;$('mute').textContent=muted?'음소거':'사운드 ON';tone(440,.12);};$('start').onclick=()=>{reset();$('overlay').hidden=true;};document.addEventListener('visibilitychange',()=>{if(document.hidden&&!['menu','over','win'].includes(state.mode)){paused=true;$('pause').textContent='계속하기';}});reset();state.mode='menu';ui();let refresh=0;function frame(ts){const dt=Math.min(.05,(ts-last)/1000||0);last=ts;update(dt);refresh+=dt;if(refresh>.2){ui();refresh=0;}draw();requestAnimationFrame(frame);}requestAnimationFrame(frame);
if(location.search.includes('test'))window.qa={get state(){return state;},reset,build,upgrade,startWave,spawn,update,position,length,select(i){selected=i;ui();},spec:{TYPES,ENEMIES,WAVES,SITES},stop(){paused=true;},run(dt){paused=false;update(dt);paused=true;}};
})();




